package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Monday, 13 April, 2026 3:28:29 PM IST
*/

public interface CalculatorOperations 
{
  float add (float a, float b);
  float sub (float a, float b);
  float mul (float a, float b);
  float div (float a, float b);
} // interface CalculatorOperations
